#
# See https://developer.github.com/v4/object/user/
#
query UserRepositoryListQuery($userLogin: String!, $first: Int!, $after: String) {
  user(login: $userLogin) {
    repositories(
      first: $first,
      after: $after,
      orderBy: {field: CREATED_AT, direction: DESC},
    ) {
      edges {
        cursor
        node {
          ...repositoryFields
        }
      }
      pageInfo {
        hasNextPage
      }
    }
  }
}

fragment repositoryFields on Repository {
  id
  name
  description
  stargazers(first: 0) {
    totalCount
  }
  createdAt
}
